with seed(
  title_tc, short_description_tc, description_tc, organizer_name,
  venue_name, address, district, mtr_station,
  start_date, end_date, start_time, end_time,
  price_type, price_display_mode, price_label,
  age_min, age_max, activity_category, category, tags,
  is_free, is_sen_friendly, is_indoor, is_outdoor,
  registration_required, booking_method, booking_note,
  contact_phone, registration_url, official_url, source_url,
  cta_type, cta_label, parent_requirement, language,
  is_walk_in, is_featured
) as (
  values
  (
    '國際中秋綵燈匯',
    '維多利亞公園大型中秋綵燈活動，展出南京大型燈組、世界綵燈大街及多項節慶裝置。',
    '香港旅遊發展局於維多利亞公園舉辦國際中秋綵燈匯，設有大型主題綵燈、來自不同國家的節慶綵燈及香港特色燈組。一般亮燈時間為下午6:30至晚上11:00；9月25日延長至午夜12:00。詳情及臨時安排以官方最新公布為準。',
    '香港旅遊發展局',
    '維多利亞公園',
    '香港島銅鑼灣興發街1號維多利亞公園',
    '灣仔區',
    '天后／銅鑼灣',
    date '2026-09-17', date '2026-09-27', time '18:30', time '23:00',
    'free','free','免費',
    null,null,'節慶活動','festival',array['中秋','綵燈','免費','戶外','維多利亞公園']::text[],
    true,false,false,true,
    false,'none','毋須平台報名，入場及人流安排以官方公布為準。',
    null,null,
    'https://www.discoverhongkong.com/tc/events/international-lantern-spectacular.html',
    'https://www.discoverhongkong.com/tc/events/international-lantern-spectacular.html',
    'official','查看官方資料','not_specified','繁體中文',
    true,true
  ),
  (
    '丙午年中秋光影裝置｜香港文化中心露天廣場',
    '尖沙咀香港文化中心露天廣場中秋光影裝置，免費入場。',
    '康樂及文化事務署丙午年中秋綵燈會其中一部分，中秋光影裝置於香港文化中心露天廣場展出。亮燈時間一般為下午6:30至晚上11:00；9月25日延長至午夜12:00。詳情以官方最新公布為準。',
    '康樂及文化事務署',
    '香港文化中心露天廣場',
    '九龍尖沙咀梳士巴利道10號香港文化中心露天廣場',
    '油尖旺區',
    '尖沙咀',
    date '2026-09-17', date '2026-10-11', time '18:30', time '23:00',
    'free','free','免費',
    null,null,'節慶活動','festival',array['中秋','光影裝置','免費','戶外','尖沙咀']::text[],
    true,false,false,true,
    false,'none','毋須平台報名。',
    '+852 2591 1340',null,
    'https://www.cpo.gov.hk/zh-hk/event/tc-mid-autumn-lantern-carnival-2026/',
    'https://www.cpo.gov.hk/zh-hk/event/tc-mid-autumn-lantern-carnival-2026/',
    'official','查看官方資料','not_specified','粵語',
    true,false
  ),
  (
    '大坑舞火龍 2026',
    '中秋期間大坑傳統舞火龍盛會，火龍穿梭大坑街道，9月25日部分表演延伸至維多利亞公園。',
    '2026年大坑舞火龍於9月24日至26日舉行。官方公布時間分別為9月24日晚上7:00至10:00、9月25日晚上7:00至11:30、9月26日晚上7:00至10:00。最佳觀賞位置為浣紗街一帶，活動期間可能有人流管制。',
    '大坑坊眾福利會',
    '大坑一帶（浣紗街）',
    '香港島大坑浣紗街一帶',
    '灣仔區',
    '天后／銅鑼灣',
    date '2026-09-24', date '2026-09-26', null,null,
    'unknown','unknown','詳情請見官方網站',
    null,null,'文化節慶','festival',array['中秋','舞火龍','非物質文化遺產','戶外','大坑']::text[],
    false,false,false,true,
    false,'none','每日表演時間不同，請先查看官方頁面。',
    null,null,
    'https://www.discoverhongkong.com/tc/events/tai-hang-s-fire-dragon-dance.html',
    'https://www.discoverhongkong.com/tc/events/tai-hang-s-fire-dragon-dance.html',
    'official','查看官方時間','not_specified','繁體中文',
    true,true
  ),
  (
    '薄扶林村中秋舞火龍 2026',
    '薄扶林村傳統中秋舞火龍，巡遊至華富邨及瀑布灣公園。',
    '薄扶林村於中秋節舉行傳統舞火龍。火龍由村內出發，經村內街巷及相關祭祀地點，最後到瀑布灣公園進行「龍歸滄海」儀式。官方列明免費觀賞。',
    'Pokfulam Village Fire Dragon Association',
    '薄扶林村、華富邨及瀑布灣公園',
    '香港島薄扶林',
    '南區',
    '香港大學／轉乘巴士',
    date '2026-09-25', date '2026-09-25', time '18:30', time '23:59',
    'free','free','免費觀賞',
    null,null,'文化節慶','festival',array['中秋','舞火龍','免費','戶外','薄扶林']::text[],
    true,false,false,true,
    false,'none','現場觀賞，詳情以官方公布為準。',
    null,null,
    'https://www.discoverhongkong.com/eng/events/event.id89862.pok-fu-lam-village-mid-autumn-fire-dragon-dance.html',
    'https://www.discoverhongkong.com/eng/events/event.id89862.pok-fu-lam-village-mid-autumn-fire-dragon-dance.html',
    'official','查看官方資料','not_specified','繁體中文',
    true,false
  ),
  (
    '「嶼月高昇‧處處是景」東涌海濱花燈節2026',
    '東涌海濱大型花燈節，設5米高月兔及互動光影裝置，免費入場。',
    '東涌東海濱長廊及東涌東海濱長廊2.0舉行花燈節。一般由晚上6:00亮燈；不同區域結束時間不同，9月25日至27日亦有延長安排。詳情以官方頁面為準。',
    '土木工程拓展署南拓展及可持續大嶼辦事處',
    '東涌東海濱長廊及東涌東海濱長廊2.0',
    '離島東涌海濱路',
    '離島區',
    '東涌',
    date '2026-09-17', date '2026-10-05', time '18:00', null,
    'free','free','免費',
    null,null,'節慶活動','festival',array['中秋','花燈','免費','戶外','東涌']::text[],
    true,false,false,true,
    false,'none','不同展區亮燈時間不同，請查看官方頁面。',
    '+852 2195 0819',null,
    'https://www.discoverhongkong.com/tc/events/event.id89022.-%E5%B6%BC%E6%9C%88%E9%AB%98%E6%98%87-%E8%99%95%E8%99%95%E6%98%AF%E6%99%AF-%E6%9D%B1%E6%B6%8C%E6%B5%B7%E6%BF%B1%E8%8A%B1%E7%87%88%E7%AF%802026.html',
    'https://www.discoverhongkong.com/tc/events/event.id89022.-%E5%B6%BC%E6%9C%88%E9%AB%98%E6%98%87-%E8%99%95%E8%99%95%E6%98%AF%E6%99%AF-%E6%9D%B1%E6%B6%8C%E6%B5%B7%E6%BF%B1%E8%8A%B1%E7%87%88%E7%AF%802026.html',
    'official','查看官方資料','not_specified','繁體中文',
    true,true
  ),
  (
    '親子隨玩現場：畫畫不尋常｜9月27日',
    'M+免費親子隨玩活動，小朋友可用特製「畫筆」在巨型畫紙上創作。',
    '活動以自助形式進行，免費及無須預約。M+教學人員利用日常物品手柄設計不尋常畫筆，讓家庭在巨型畫紙上留下創作印記。適合任何年齡兒童在成人陪同下參與。',
    'M+',
    'M+ 工作室2',
    '九龍西九文化區博物館道38號 M+',
    '油尖旺區',
    '九龍／柯士甸',
    date '2026-09-27', date '2026-09-27', time '14:00', time '17:00',
    'free','free','免費',
    0,null,'親子工作坊','workshop',array['M+','親子','畫畫','免費','室內']::text[],
    true,false,true,false,
    false,'none','即場參加；如工作室名額已滿，需按現場指示排隊。',
    null,null,
    'https://www.mplus.org.hk/tc/events/family-drop-in-unusual-drawing/',
    'https://www.mplus.org.hk/tc/events/family-drop-in-unusual-drawing/',
    'official','查看官方資料','parent_required','廣東話、英語',
    true,false
  ),
  (
    '親子隨玩現場：日常的奇妙時刻｜9月27日',
    'M+免費流動故事劇場，透過繪本與孩子發掘日常用品背後的設計巧思。',
    '活動免費、無須預約，適合任何年齡兒童在家長陪同下參與。每節約20分鐘，設廣東話及英語場次，座位有限，先到先得。',
    'M+',
    'M+ 學舍',
    '九龍西九文化區博物館道38號 M+',
    '油尖旺區',
    '九龍／柯士甸',
    date '2026-09-27', date '2026-09-27', time '14:00', time '16:50',
    'free','free','免費',
    0,null,'親子故事活動','education',array['M+','親子','故事','免費','室內']::text[],
    true,false,true,false,
    false,'none','即場參加；每節約20分鐘，座位有限。',
    null,null,
    'https://www.mplus.org.hk/tc/events/family-drop-in-story-time-with-everyday-wonders/',
    'https://www.mplus.org.hk/tc/events/family-drop-in-story-time-with-everyday-wonders/',
    'official','查看官方場次','parent_required','廣東話、英語',
    true,false
  ),
  (
    '親子隨玩現場：畫畫不尋常｜10月18日',
    'M+免費親子隨玩活動，小朋友可用特製「畫筆」在巨型畫紙上創作。',
    '活動以自助形式進行，免費及無須預約。適合任何年齡兒童在成人陪同下參與。',
    'M+','M+ 工作室2','九龍西九文化區博物館道38號 M+','油尖旺區','九龍／柯士甸',
    date '2026-10-18',date '2026-10-18',time '14:00',time '17:00',
    'free','free','免費',0,null,'親子工作坊','workshop',array['M+','親子','畫畫','免費','室內']::text[],
    true,false,true,false,false,'none','即場參加。',
    null,null,
    'https://www.mplus.org.hk/tc/events/family-drop-in-unusual-drawing/',
    'https://www.mplus.org.hk/tc/events/family-drop-in-unusual-drawing/',
    'official','查看官方資料','parent_required','廣東話、英語',true,false
  ),
  (
    '親子隨玩現場：日常的奇妙時刻｜10月18日',
    'M+免費親子故事活動，以繪本探索日常設計。',
    '活動免費、無須預約。當日設多個廣東話及英語場次，每節約20分鐘，座位有限。',
    'M+','M+ 學舍','九龍西九文化區博物館道38號 M+','油尖旺區','九龍／柯士甸',
    date '2026-10-18',date '2026-10-18',time '14:00',time '16:50',
    'free','free','免費',0,null,'親子故事活動','education',array['M+','親子','故事','免費','室內']::text[],
    true,false,true,false,false,'none','即場參加；每節約20分鐘。',
    null,null,
    'https://www.mplus.org.hk/tc/events/family-drop-in-story-time-with-everyday-wonders/',
    'https://www.mplus.org.hk/tc/events/family-drop-in-story-time-with-everyday-wonders/',
    'official','查看官方場次','parent_required','廣東話、英語',true,false
  ),
  (
    '親子隨玩現場：畫畫不尋常｜10月25日',
    'M+免費親子隨玩活動，小朋友可用特製「畫筆」在巨型畫紙上創作。',
    '活動以自助形式進行，免費及無須預約。適合任何年齡兒童在成人陪同下參與。',
    'M+','M+ 工作室2','九龍西九文化區博物館道38號 M+','油尖旺區','九龍／柯士甸',
    date '2026-10-25',date '2026-10-25',time '14:00',time '17:00',
    'free','free','免費',0,null,'親子工作坊','workshop',array['M+','親子','畫畫','免費','室內']::text[],
    true,false,true,false,false,'none','即場參加。',
    null,null,
    'https://www.mplus.org.hk/tc/events/family-drop-in-unusual-drawing/',
    'https://www.mplus.org.hk/tc/events/family-drop-in-unusual-drawing/',
    'official','查看官方資料','parent_required','廣東話、英語',true,false
  ),
  (
    '親子隨玩現場：日常的奇妙時刻｜10月25日',
    'M+免費親子故事活動，以繪本探索日常設計。',
    '活動免費、無須預約。當日設多個廣東話及英語場次，每節約20分鐘，座位有限。',
    'M+','M+ 學舍','九龍西九文化區博物館道38號 M+','油尖旺區','九龍／柯士甸',
    date '2026-10-25',date '2026-10-25',time '14:00',time '16:50',
    'free','free','免費',0,null,'親子故事活動','education',array['M+','親子','故事','免費','室內']::text[],
    true,false,true,false,false,'none','即場參加；每節約20分鐘。',
    null,null,
    'https://www.mplus.org.hk/tc/events/family-drop-in-story-time-with-everyday-wonders/',
    'https://www.mplus.org.hk/tc/events/family-drop-in-story-time-with-every-wonders/',
    'official','查看官方場次','parent_required','廣東話、英語',true,false
  ),
  (
    '法式光影－莫奈親子繪畫工作坊',
    '5至12歲小朋友可與一位家長參加，以莫奈為主題的英語親子繪畫工作坊。',
    '香港公共圖書館活動。對象為5至12歲小朋友及其一位家長，工作坊以英語進行，免費入場。官方資料指可由10月10日起親臨圖書館2樓櫃檯或致電登記留座，名額有限，先到先得。',
    '香港公共圖書館／香港法國文化協會',
    '屏山天水圍公共圖書館（推廣活動室）',
    '新界天水圍聚星路1號屏山天水圍文化康樂大樓',
    '元朗區',
    '天水圍',
    date '2026-10-24',date '2026-10-24',time '15:00',time '16:30',
    'free','free','免費',5,12,'親子工作坊','arts',array['親子','繪畫','莫奈','免費','圖書館','英語']::text[],
    true,false,true,false,true,'contact','10月10日起可親臨圖書館2樓櫃檯或致電登記，名額有限。',
    '2126 7520',null,
    'https://www.hkpl.gov.hk/tc/extension-activities/event-detail/304563/french-vibe-monet-parent-child-painting-workshop',
    'https://www.hkpl.gov.hk/tc/extension-activities/event-detail/304563/french-vibe-monet-parent-child-painting-workshop',
    'contact','查看報名詳情','parent_required','英語',false,true
  ),
  (
    '專題故事劇場2026：愛因斯坦成長之旅｜屯門',
    '故事劇場加指南針小手工，讓小朋友從愛因斯坦成長故事探索科學與好奇心。',
    '香港公共圖書館專題故事劇場。故事探險隊帶領小朋友認識愛因斯坦的成長歷程，故事劇場後會一起製作簡單指南針。報名或入場安排以官方頁面最新資料為準。',
    '香港公共圖書館',
    '屯門公共圖書館（推廣活動室）',
    '新界屯門屯喜路1號屯門公共圖書館',
    '屯門區',
    '屯門',
    date '2026-10-24',date '2026-10-24',time '11:30',time '12:30',
    'unknown','unknown','詳情請見官方網站',null,null,'兒童故事活動','education',array['兒童','故事劇場','科學','愛因斯坦','圖書館']::text[],
    false,false,true,false,false,'none','報名／入場安排以香港公共圖書館最新公布為準。',
    null,null,
    'https://www.hkpl.gov.hk/tc/extension-activities/sub-event/301243/thematic-storytelling-workshops-2026-einstein-s-journey-of-growth?page=2',
    'https://www.hkpl.gov.hk/tc/extension-activities/sub-event/301243/thematic-storytelling-workshops-2026-einstein-s-journey-of-growth?page=2',
    'official','查看官方資料','not_specified','粵語',false,false
  ),
  (
    '「做個小小規劃師」工作坊｜屯門',
    '小朋友可在基礎地圖上利用樂高及美術材料規劃模擬城市。',
    '工作坊以城市規劃為主題，參加者可在基礎地圖上規劃模擬城市，活動材料包括樂高積木、硬卡紙、顏色水筆等。參加及報名安排以香港公共圖書館最新公布為準。',
    '香港公共圖書館',
    '屯門公共圖書館',
    '新界屯門屯喜路1號屯門公共圖書館',
    '屯門區',
    '屯門',
    date '2026-10-24',date '2026-10-24',time '15:00',time '16:30',
    'unknown','unknown','詳情請見官方網站',null,null,'兒童工作坊','education',array['兒童','城市規劃','LEGO','工作坊','圖書館']::text[],
    false,false,true,false,false,'none','報名／入場安排以香港公共圖書館最新公布為準。',
    null,null,
    'https://www.hkpl.gov.hk/tc/extension-activities/event/296868/be-a-little-town-planner-workshops',
    'https://www.hkpl.gov.hk/tc/extension-activities/event/296868/be-a-little-town-planner-workshops',
    'official','查看官方資料','not_specified','粵語',false,false
  ),
  (
    '兒童故事時間：歡樂萬聖節｜深水埗',
    '兒童故事時間加南瓜小手工，主題為歡樂萬聖節。',
    '香港公共圖書館兒童故事時間，透過故事訓練孩子觀察力和想像力，並製作南瓜小手工。參加及入場安排以官方最新公布為準。',
    '香港公共圖書館',
    '深水埗公共圖書館（推廣活動室）',
    '九龍深水埗元州街59-63號北河街市政大廈',
    '深水埗區',
    '深水埗',
    date '2026-10-25',date '2026-10-25',time '14:00',time '15:00',
    'unknown','unknown','詳情請見官方網站',null,null,'兒童故事活動','education',array['兒童','故事時間','萬聖節','手工','圖書館']::text[],
    false,false,true,false,false,'none','參加及入場安排以官方最新公布為準。',
    null,null,
    'https://www.hkpl.gov.hk/tc/extension-activities/event/303033/storytelling-for-children-cantonese',
    'https://www.hkpl.gov.hk/tc/extension-activities/event/303033/storytelling-for-children-cantonese',
    'official','查看官方資料','not_specified','粵語',false,false
  ),
  (
    '「李小龍迷影相館」家庭活動｜9月27日',
    '香港文化博物館家庭活動，親子可於兒童探知館入口參與李小龍主題影相體驗。',
    '香港文化博物館「李小龍迷影相館」家庭活動逢星期日及公眾假期舉行，對象為兒童及家長，無須登記，可即場參加。本紀錄為2026年9月27日場次。',
    '香港文化博物館',
    '香港文化博物館兒童探知館入口（地下）',
    '新界沙田文林路1號香港文化博物館',
    '沙田區',
    '車公廟／沙田',
    date '2026-09-27',date '2026-09-27',time '16:00',time '17:00',
    'unknown','unknown','詳情請見官方網站',null,null,'親子活動','family',array['親子','博物館','李小龍','影相','沙田']::text[],
    false,false,true,false,false,'none','無須登記，即場參加。',
    null,null,
    'https://www.heritagemuseum.gov.hk/en/activities/activity_detail_BruceLeeFansPhotoStudioFamilyProgramme.html',
    'https://www.heritagemuseum.gov.hk/en/activities/activity_detail_BruceLeeFansPhotoStudioFamilyProgramme.html',
    'official','查看官方資料','parent_required','粵語',true,false
  )
)
insert into public.events (
  title_tc, short_description_tc, description_tc, organizer_name,
  venue_name, address, district, mtr_station,
  start_date, end_date, start_time, end_time,
  price_type, price_display_mode, price_label,
  age_min, age_max, activity_category, category, tags,
  is_free, is_sen_friendly, is_indoor, is_outdoor,
  registration_required, booking_method, booking_note,
  contact_phone, registration_url, official_url, source_url,
  cta_type, cta_label, parent_requirement, language,
  is_walk_in, is_featured,
  status, source_type, ai_extraction_status,
  published_at, reviewed_at, admin_review_note,
  show_on_calendar, hidden_pending_confirmation,
  platform_takes_booking, platform_takes_payment
)
select
  s.title_tc, s.short_description_tc, s.description_tc, s.organizer_name,
  s.venue_name, s.address, s.district, s.mtr_station,
  s.start_date, s.end_date, s.start_time, s.end_time,
  s.price_type, s.price_display_mode, s.price_label,
  s.age_min, s.age_max, s.activity_category, s.category, s.tags,
  s.is_free, s.is_sen_friendly, s.is_indoor, s.is_outdoor,
  s.registration_required, s.booking_method, s.booking_note,
  s.contact_phone, s.registration_url, s.official_url, s.source_url,
  s.cta_type, s.cta_label, s.parent_requirement, s.language,
  s.is_walk_in, s.is_featured,
  'published','url','not_available',
  now(),now(),'Pre-launch seed: manually verified against the official source on 2026-09-20.',
  true,false,false,false
from seed s
where not exists (
  select 1 from public.events e
  where e.title_tc=s.title_tc
    and e.start_date=s.start_date
    and coalesce(e.source_url,'')=coalesce(s.source_url,'')
);
